import { FormEvent, useEffect, useRef, useState } from 'react';
import { AdminApiError, callAdmin } from '../lib/adminApi';

interface AiAnswer { answer:string; highlights:Array<{severity:'info'|'warning'|'critical';title:string;detail:string}>; recommended_actions:Array<{title:string;reason:string;requires_approval:boolean}>; data_freshness_note:string; }
interface AiCampaign { id:string;name:string;subject:string;previewText:string;htmlBody:string;textBody:string;segment:string;rationale:string;audienceCount:number;heading:string;body:string;cta:string;appUrl:string;model:string;status:'draft'|'approved'|'cancelled'; }
interface Exchange { id:string; question:string; response:AiAnswer; model:string; campaign:AiCampaign|null; }
const SUGGESTIONS=['What is the biggest onboarding problem right now?','Are any providers unhealthy or unusually slow?','Create the best campaign for our largest recoverable onboarding drop-off.','Summarize today’s operational risks.'];

export default function AiAssistantPage(){
  const [question,setQuestion]=useState(''),[history,setHistory]=useState<Exchange[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[copied,setCopied]=useState<string|null>(null),[campaignBusy,setCampaignBusy]=useState<string|null>(null);
  const endRef=useRef<HTMLDivElement|null>(null),inputRef=useRef<HTMLTextAreaElement|null>(null);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'end'});},[history,loading]);
  const ask=async(event?:FormEvent,override?:string)=>{event?.preventDefault();const current=(override??question).trim();if(current.length<3||loading)return;setQuestion('');setLoading(true);setError(null);try{const result=await callAdmin<{answer:AiAnswer;model:string;campaign:AiCampaign|null}>('admin-ai-assistant',{method:'POST',body:{question:current,request_id:crypto.randomUUID()}});setHistory(items=>[...items,{id:crypto.randomUUID(),question:current,response:result.answer,model:result.model,campaign:result.campaign}]);}catch(err){setQuestion(current);setError(err instanceof AdminApiError?err.message:'The assistant is unavailable');}finally{setLoading(false);inputRef.current?.focus();}};
  const clear=()=>{if(history.length>0&&!window.confirm('Clear this conversation from the screen? This will not delete reports, campaigns or operational data.'))return;setHistory([]);setError(null);setCopied(null);setQuestion('');inputRef.current?.focus();};
  const copy=async(item:Exchange)=>{try{await navigator.clipboard.writeText(item.response.answer);setCopied(item.id);window.setTimeout(()=>setCopied(value=>value===item.id?null:value),1800);}catch{setError('Could not copy the response.');}};
  const campaignAction=async(exchangeId:string,campaignId:string,action:'approve'|'cancel')=>{if(action==='approve'&&!window.confirm('Approve and automatically send this AI-generated campaign to the displayed consent-eligible audience?'))return;if(action==='cancel'&&!window.confirm('Reject this AI-generated campaign draft?'))return;setCampaignBusy(campaignId);setError(null);try{const result=await callAdmin<{recipients?:number}>('admin-campaigns',{method:'POST',body:{action,campaign_id:campaignId}});setHistory(items=>items.map(item=>item.id===exchangeId&&item.campaign?{...item,campaign:{...item.campaign,status:action==='approve'?'approved':'cancelled'}}:item));if(action==='approve')window.alert(`Campaign approved and queued for ${result.recipients??0} consent-eligible recipients.`);}catch(err){setError(err instanceof AdminApiError?err.message:'Campaign action failed');}finally{setCampaignBusy(null);}};
  const onKeyDown=(event:React.KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void ask();}};
  return <div className="chat-page">
    <header className="chat-header"><div><h2>KaysPay AI</h2><div className="chat-status"><span/>Groq · GPT‑OSS 120B · read-only</div></div><div className="chat-header-actions"><button className="secondary" onClick={clear}>New chat</button><button className="secondary" disabled={history.length===0} onClick={clear}>Clear</button></div></header>
    <div className="chat-privacy">AI reads sanitized operational summaries only. Sending campaigns, changing services and financial actions always require approval.</div>
    <section className={`chat-thread ${history.length===0?'empty':''}`}>
      {history.length===0&&<div className="chat-welcome"><div className="chat-logo">AI</div><h1>What would you like to know?</h1><p>Ask about onboarding, campaigns, provider health, sales or operational performance.</p><div className="chat-prompt-grid">{SUGGESTIONS.map(item=><button key={item} disabled={loading} onClick={()=>void ask(undefined,item)}><span>{item}</span><b>→</b></button>)}</div></div>}
      {history.map(item=><article className="chat-exchange" key={item.id}><div className="chat-user-row"><div className="chat-user-message">{item.question}</div><div className="chat-avatar user">You</div></div><div className="chat-assistant-row"><div className="chat-avatar assistant">AI</div><div className="chat-assistant-message"><div className="chat-message-label">KaysPay AI</div><div className="chat-answer-copy">{item.response.answer}</div><details className="chat-analysis"><summary>View analysis and recommended actions <span>⌄</span></summary><div className="chat-analysis-body">{item.response.highlights.length>0&&<div className="chat-insights">{item.response.highlights.map((h,i)=><div className={`chat-insight ${h.severity}`} key={i}><i/><div><strong>{h.title}</strong><p>{h.detail}</p></div></div>)}</div>}{item.response.recommended_actions.length>0&&<div className="chat-actions"><h4>Recommended actions</h4>{item.response.recommended_actions.map((action,i)=><div key={i}><span>{i+1}</span><p><strong>{action.title}</strong>{action.requires_approval&&<em>Approval required</em>}<small>{action.reason}</small></p></div>)}</div>}<p className="chat-freshness">{item.response.data_freshness_note}</p></div></details>{item.campaign&&<section className={`chat-campaign-card ${item.campaign.status}`}><div className="chat-campaign-head"><div><span>AI campaign draft</span><h3>{item.campaign.name}</h3></div><b>{item.campaign.audienceCount.toLocaleString()} recipients</b></div><div className="chat-campaign-meta"><div><small>Audience</small><strong>{item.campaign.segment.replace(/_/g,' ')}</strong></div><div><small>Subject</small><strong>{item.campaign.subject}</strong></div><p>{item.campaign.rationale}</p></div><div className="chat-email-preview" aria-label="AI-generated campaign preview"><div className="chat-email-brand">KaysPay</div><div className="chat-email-content"><h2>{item.campaign.heading}</h2><p>{item.campaign.body}</p><span className="chat-email-cta">{item.campaign.cta}</span><small>For your security, KaysPay will never ask for your PIN, password, or OTP by email.</small></div></div><div className="chat-campaign-controls">{item.campaign.status==='draft'?<><button className="primary" disabled={campaignBusy===item.campaign.id} onClick={()=>void campaignAction(item.id,item.campaign!.id,'approve')}>{campaignBusy===item.campaign.id?'Processing…':'Approve & send'}</button><button className="secondary" disabled={campaignBusy===item.campaign.id} onClick={()=>void campaignAction(item.id,item.campaign!.id,'cancel')}>Reject draft</button></>:<span className={`badge ${item.campaign.status}`}>{item.campaign.status==='approved'?'Approved and queued':'Draft rejected'}</span>}</div></section>}<div className="chat-message-tools"><button onClick={()=>void copy(item)}>{copied===item.id?'Copied':'Copy'}</button><span>{item.model.replace('openai/','')}</span></div></div></div></article>)}
      {loading&&<div className="chat-assistant-row chat-thinking"><div className="chat-avatar assistant">AI</div><div className="chat-assistant-message"><div className="chat-message-label">KaysPay AI</div><div className="typing-dots"><i/><i/><i/></div><span>Analyzing current KaysPay data…</span></div></div>}
      <div ref={endRef}/>
    </section>
    <div className="chat-composer-wrap">{error&&<div className="chat-error">{error}</div>}<form className="chat-composer" onSubmit={event=>void ask(event)}><textarea ref={inputRef} required minLength={3} maxLength={1000} rows={1} value={question} onKeyDown={onKeyDown} onChange={e=>setQuestion(e.target.value)} placeholder="Message KaysPay AI…"/><button aria-label="Send message" disabled={loading||question.trim().length<3}>↑</button></form><div className="chat-composer-note"><span>Enter to send · Shift+Enter for a new line</span><span>Usage managed by Groq</span></div></div>
  </div>;
}
