import { useEffect, useState } from 'react';
import { AdminApiError, callAdmin } from '../lib/adminApi';

type Segment = 'registered_not_verified' | 'verified_kyc_incomplete' | 'kyc_completed_not_funded' | 'funded_not_purchased' | 'inactive';
interface RecipientDelivery { status:string; delivered_at:string|null; bounced_at:string|null; opened_at:string|null; clicked_at:string|null; complained_at:string|null; delivery_delayed_at:string|null; }
interface Campaign { id:string; name:string; subject:string; segment:Segment; status:string; scheduled_for:string|null; created_at:string; approved_at:string|null; marketing_campaign_recipients:RecipientDelivery[]; }
interface SegmentCount { segment:Segment; count:number; }
interface GeneratedCampaign { id:string; name:string; subject:string; previewText:string; htmlBody:string; textBody:string; segment:Segment; rationale:string; audienceCount:number; }
const LABELS:Record<Segment,string>={registered_not_verified:'Registered, email not verified',verified_kyc_incomplete:'Verified, KYC incomplete',kyc_completed_not_funded:'KYC completed, not funded',funded_not_purchased:'Funded, no first purchase',inactive:'Inactive customers'};

export default function CampaignsPage(){
  const [campaigns,setCampaigns]=useState<Campaign[]>([]),[segments,setSegments]=useState<SegmentCount[]>([]);
  const [prompt,setPrompt]=useState('Review onboarding and choose the best recovery opportunity. Create a clear, helpful email.'),[draft,setDraft]=useState<GeneratedCampaign|null>(null);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  const load=()=>{setLoading(true);callAdmin<{campaigns:Campaign[];segments:SegmentCount[]}>('admin-campaigns').then(r=>{setCampaigns(r.campaigns);setSegments(r.segments);}).catch(e=>setError(e instanceof AdminApiError?e.message:'Could not load campaigns')).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const generate=async()=>{setBusy('generate');setError(null);setMessage(null);try{const result=await callAdmin<{campaign:GeneratedCampaign}>('admin-campaigns',{method:'POST',body:{action:'generate',prompt}});setDraft(result.campaign);setMessage('The assistant analyzed consent-eligible customers and prepared this campaign. Nothing has been sent.');load();}catch(err){setError(err instanceof AdminApiError?err.message:'The assistant could not create a campaign');}finally{setBusy(null);}};
  const sendTest=async()=>{if(!draft)return;setBusy('test');setError(null);setMessage(null);try{await callAdmin('admin-campaigns',{method:'POST',body:{action:'test',subject:draft.subject,html_body:draft.htmlBody,text_body:draft.textBody}});setMessage('Test sent only to your signed-in admin email.');}catch(err){setError(err instanceof AdminApiError?err.message:'Test email failed');}finally{setBusy(null);}};
  const act=async(id:string,action:'approve'|'pause'|'cancel')=>{if(action==='approve'&&!window.confirm('Approve this AI-generated campaign and send it automatically? The eligible recipient list will be frozen and processed in duplicate-safe batches.'))return;setBusy(id);setError(null);setMessage(null);try{const r=await callAdmin<{recipients?:number}>('admin-campaigns',{method:'POST',body:{action,campaign_id:id}});setMessage(action==='approve'?`Approved for ${r.recipients??0} consent-eligible recipients. Automatic delivery starts now.`:`Campaign ${action}d.`);if(action==='approve'&&draft?.id===id)setDraft(null);load();}catch(err){setError(err instanceof AdminApiError?err.message:'Campaign action failed');}finally{setBusy(null);}};
  return <div>
    <div className="page-header campaign-header"><div><h2>AI Campaign Assistant</h2><p className="muted">Ask for an outcome. The assistant analyzes onboarding, chooses the audience, writes and designs the email.</p></div></div>
    <div className="campaign-consent-note"><strong>Human approval required:</strong> the assistant can prepare campaigns, but only your explicit approval can queue an email. Consent and suppression checks run again at approval and delivery.</div>
    {error&&<div className="error-text">{error}</div>}{message&&<div className="success-text">{message}</div>}
    <div className="summary-grid campaign-segments">{segments.map(s=><div className="stat-card" key={s.segment}><div className="stat-value">{s.count.toLocaleString()}</div><div className="stat-label">{LABELS[s.segment]}</div></div>)}</div>
    <div className="card ai-composer"><div className="ai-title"><div className="ai-mark">AI</div><div><h3>What should we improve?</h3><p className="muted">You can leave the recommendation as written and let the assistant choose.</p></div></div><textarea maxLength={1000} rows={4} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Example: Find customers who stopped before funding and encourage them to continue."/><div className="ai-actions"><button className="primary" disabled={busy==='generate'} onClick={generate}>{busy==='generate'?'Analyzing and designing…':'Analyze & create campaign'}</button><span className="muted">Uses aggregated insights only—never customer financial details.</span></div></div>
    {draft&&<div className="card ai-draft"><div className="row between ai-draft-heading"><div><span className="badge approved">AI draft · not sent</span><h3>{draft.name}</h3></div><strong>{draft.audienceCount.toLocaleString()} eligible recipients</strong></div><div className="ai-rationale"><strong>Why this campaign</strong><p>{draft.rationale}</p></div><div className="ai-review-grid"><div><dl className="ai-details"><div><dt>Audience</dt><dd>{LABELS[draft.segment]}</dd></div><div><dt>Subject</dt><dd>{draft.subject}</dd></div><div><dt>Preview text</dt><dd>{draft.previewText}</dd></div></dl><div className="ai-approval-actions"><button className="primary" disabled={busy===draft.id} onClick={()=>act(draft.id,'approve')}>Approve &amp; send automatically</button><button className="secondary" disabled={busy==='test'} onClick={sendTest}>{busy==='test'?'Sending test…':'Send test to me'}</button><button className="danger" disabled={busy===draft.id} onClick={()=>act(draft.id,'cancel')}>Reject draft</button></div></div><iframe className="campaign-preview" sandbox="" srcDoc={draft.htmlBody} title="AI-generated email preview" /></div></div>}
    <div className="card"><h3>Campaign history</h3>{loading?<p className="muted">Loading…</p>:campaigns.length===0?<p className="muted">No campaigns yet.</p>:<div className="table-scroll"><table><thead><tr><th>Campaign</th><th>Segment</th><th>Status</th><th>Created</th><th>Approved</th><th>Delivery</th><th>Engagement</th><th>Automatic send</th><th>Actions</th></tr></thead><tbody>{campaigns.map(c=>{const rows=c.marketing_campaign_recipients;const count=(field:keyof RecipientDelivery)=>rows.filter(r=>Boolean(r[field])).length;const queued=rows.filter(r=>['pending','sending'].includes(r.status)).length;const failed=rows.filter(r=>r.status==='failed').length;return <tr key={c.id}><td><strong>{c.name}</strong><br/><span className="muted">{c.subject}</span></td><td>{LABELS[c.segment]}</td><td><span className={`badge ${c.status}`}>{c.status}</span></td><td className="muted">{new Date(c.created_at).toLocaleString('en-GB')}</td><td className="muted">{c.approved_at?new Date(c.approved_at).toLocaleString('en-GB'):'—'}</td><td><span className="recipient-count">Queued: {queued}</span><span className="recipient-count">Accepted: {rows.filter(r=>r.status==='sent').length}</span><span className="recipient-count delivery-good">Delivered: {count('delivered_at')}</span><span className="recipient-count delivery-bad">Failed/bounced: {failed}</span></td><td><span className="recipient-count">Opened: {count('opened_at')}</span><span className="recipient-count">Clicked: {count('clicked_at')}</span><span className="recipient-count delivery-bad">Complaints: {count('complained_at')}</span></td><td>{c.scheduled_for?new Date(c.scheduled_for).toLocaleString():'Immediately after approval'}</td><td><div className="campaign-actions">{c.status==='draft'&&<button className="primary" disabled={busy===c.id} onClick={()=>act(c.id,'approve')}>Approve &amp; send</button>}{['approved','sending'].includes(c.status)&&<button className="secondary" disabled={busy===c.id} onClick={()=>act(c.id,'pause')}>Pause</button>}{['paused','draft'].includes(c.status)&&<button className="danger" disabled={busy===c.id} onClick={()=>act(c.id,'cancel')}>Cancel</button>}</div></td></tr>;})}</tbody></table></div>}</div>
  </div>;
}
