import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminApiError, callAdmin } from '../lib/adminApi';

interface Recommendation {title:string;reason:string;requires_approval:boolean}
interface Analysis {summary:string;likely_cause:string;impact:string;recommendations:Recommendation[]}
interface Incident {fingerprint:string;alert_type:string;severity:'warning'|'critical';details:Record<string,unknown>;occurrence_count:number;first_seen_at:string;last_seen_at:string;status:'open'|'acknowledged'|'resolved';acknowledged_at:string|null;resolved_at:string|null;resolution_notes:string|null;incident_analysis:Analysis|null;analysis_model:string|null;analysis_generated_at:string|null}
interface ProviderHealth {provider:string;service:string;calls_15m:number;failures_15m:number;failure_rate_15m:number|null;avg_latency_15m:number|null;calls_24h:number;failures_24h:number;last_success_at:string|null;last_failure_at:string|null}
interface Payload {incidents:Incident[];operations:{providers:ProviderHealth[]};service_controls:Array<{service:string;enabled:boolean;reason:string|null}>}
const label=(value:unknown)=>String(value??'Unknown').split('_').map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(' ');
const date=(value:string|null)=>value?new Date(value).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'}):'Never';
const controlFor=(provider:string,service:string)=>provider==='vtunaija'?'vtu':provider==='quidax'?'crypto':provider==='airalo'?'esim':service==='bank_transfer'?'transfer':service==='identity'?'identity':null;

export default function IncidentsPage(){
  const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[notes,setNotes]=useState<Record<string,string>>({}),[showResolved,setShowResolved]=useState(false);
  const load=async()=>{setLoading(true);setError(null);try{setData(await callAdmin<Payload>('admin-incidents'));}catch(e){setError(e instanceof AdminApiError?e.message:'Could not load incidents');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const visible=useMemo(()=>data?.incidents.filter(item=>showResolved||item.status!=='resolved')??[],[data,showResolved]);
  const metrics=useMemo(()=>({open:data?.incidents.filter(i=>i.status==='open').length??0,ack:data?.incidents.filter(i=>i.status==='acknowledged').length??0,critical:data?.incidents.filter(i=>i.status!=='resolved'&&i.severity==='critical').length??0,resolved:data?.incidents.filter(i=>i.status==='resolved').length??0}),[data]);
  const act=async(incident:Incident,action:'analyze'|'acknowledge'|'resolve'|'reopen')=>{setBusy(incident.fingerprint);setError(null);try{await callAdmin('admin-incidents',{method:'POST',body:{fingerprint:incident.fingerprint,action,notes:notes[incident.fingerprint]??''}});setNotes(current=>({...current,[incident.fingerprint]:''}));await load();}catch(e){setError(e instanceof AdminApiError?e.message:'Incident action failed');}finally{setBusy(null);}};
  return <div className="incident-page"><header className="incident-header"><div><span>AI-assisted operations</span><h2>Incident Centre</h2><p>Detect, investigate, acknowledge and resolve provider incidents before customers report them.</p></div><button className="secondary" disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh incidents'}</button></header>
    <div className="incident-safety">AI can diagnose and recommend. Disabling services, switching providers and retrying financial transactions always require administrator approval.</div>
    {error&&<div className="error-text">{error}</div>}
    <section className="incident-metrics"><div><span>Open</span><strong>{metrics.open}</strong></div><div><span>Acknowledged</span><strong>{metrics.ack}</strong></div><div className={metrics.critical?'critical':''}><span>Critical</span><strong>{metrics.critical}</strong></div><div><span>Resolved</span><strong>{metrics.resolved}</strong></div></section>
    <div className="incident-toolbar"><h3>Provider incidents</h3><label><input type="checkbox" checked={showResolved} onChange={e=>setShowResolved(e.target.checked)}/> Show resolved</label></div>
    {loading&&!data?<div className="card"><p className="muted">Loading incident intelligence…</p></div>:visible.length===0?<div className="incident-empty"><span>✓</span><h3>No active provider incidents</h3><p>Monitoring remains active. New degradation will appear here automatically.</p></div>:<div className="incident-list">{visible.map(incident=>{const provider=String(incident.details.provider??''),service=String(incident.details.service??''),health=data?.operations.providers.find(p=>p.provider===provider&&p.service===service),control=controlFor(provider,service),controlState=data?.service_controls.find(item=>item.service===control);return <article className={`incident-card ${incident.severity}`} key={incident.fingerprint}><div className="incident-card-head"><div><span className={`badge ${incident.severity}`}>{incident.severity}</span><span className={`incident-status ${incident.status}`}>{incident.status}</span><h3>{label(provider)} · {label(service)}</h3><p>{incident.alert_type}</p></div><div className="incident-time"><span>Last detected</span><strong>{date(incident.last_seen_at)}</strong><small>First detected {date(incident.first_seen_at)}</small></div></div>
      <div className="incident-facts"><div><span>Calls (15m)</span><strong>{health?.calls_15m??Number(incident.details.calls_15m??0)}</strong></div><div><span>Failures (15m)</span><strong>{health?.failures_15m??Number(incident.details.failures_15m??0)}</strong></div><div><span>Failure rate</span><strong>{health?.failure_rate_15m??Number(incident.details.failure_rate_15m??0)}%</strong></div><div><span>Average latency</span><strong>{health?.avg_latency_15m??Number(incident.details.avg_latency_15m??0)} ms</strong></div><div><span>Occurrences</span><strong>{incident.occurrence_count}</strong></div></div>
      {incident.incident_analysis?<section className="incident-analysis"><div className="incident-ai-label"><span>AI</span><strong>Incident assessment</strong><small>{incident.analysis_model?.replace('openai/','')} · {date(incident.analysis_generated_at)}</small></div><p>{incident.incident_analysis.summary}</p><div className="incident-analysis-grid"><div><span>Likely cause</span><p>{incident.incident_analysis.likely_cause}</p></div><div><span>Potential impact</span><p>{incident.incident_analysis.impact}</p></div></div><h4>Recommended response</h4>{incident.incident_analysis.recommendations.map((item,index)=><div className="incident-recommendation" key={index}><b>{index+1}</b><p><strong>{item.title}</strong><span>{item.reason}</span></p>{item.requires_approval&&<em>Approval required</em>}</div>)}</section>:<button className="incident-analyze" disabled={busy===incident.fingerprint} onClick={()=>void act(incident,'analyze')}>{busy===incident.fingerprint?'AI is analyzing…':'Generate AI diagnosis'}</button>}
      <div className="incident-response"><div>{control&&<><span>Service control: <strong>{controlState?.enabled===false?'Disabled':'Enabled'}</strong></span><Link to="/services">Review kill switch →</Link></>}</div><div className="incident-actions">{incident.status==='open'&&<button className="secondary" disabled={busy===incident.fingerprint} onClick={()=>void act(incident,'acknowledge')}>Acknowledge</button>}{incident.status!=='resolved'&&<><input maxLength={500} placeholder="Resolution notes" value={notes[incident.fingerprint]??''} onChange={e=>setNotes(current=>({...current,[incident.fingerprint]:e.target.value}))}/><button className="primary" disabled={busy===incident.fingerprint||(notes[incident.fingerprint]??'').trim().length<3} onClick={()=>void act(incident,'resolve')}>Mark resolved</button></>}{incident.status==='resolved'&&<button className="secondary" disabled={busy===incident.fingerprint} onClick={()=>void act(incident,'reopen')}>Reopen</button>}</div></div>
    </article>})}</div>}
  </div>;
}
