import { Fragment, useEffect, useState } from 'react';
import { AdminApiError, callAdmin } from '../lib/adminApi';

interface ProviderIssue { occurred_at:string;operation:string;outcome:string;status_code:number|null;error_code:string|null; }
interface ProviderHealth { provider:string;service:string;calls_15m:number;failures_15m:number;client_errors_15m:number;failure_rate_15m:number|null;avg_latency_15m:number|null;max_latency_15m:number|null;calls_24h:number;failures_24h:number;client_errors_24h:number;failure_rate_24h:number|null;last_success_at:string|null;last_failure_at:string|null;recent_issues:ProviderIssue[]; }
interface OperationsReport { generated_at:string; providers:ProviderHealth[]; campaigns:{active:number;failed:number;completed:number}; recipients:{pending:number;sending:number;sent:number;failed:number;suppressed:number}; }
const stateFor=(p:ProviderHealth)=>p.calls_15m===0?'idle':(p.failure_rate_15m??0)>=50?'critical':(p.failure_rate_15m??0)>=20||Number(p.avg_latency_15m)>=10000?'warning':'healthy';
const date=(value:string|null)=>value?new Date(value).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'}):'Never';
const label=(value:string)=>value.split('_').map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(' ');

export default function OperationsPage(){
  const [report,setReport]=useState<OperationsReport|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
  const load=()=>{setLoading(true);setError(null);callAdmin<{report:OperationsReport}>('admin-operations-report').then(r=>setReport(r.report)).catch(e=>setError(e instanceof AdminApiError?e.message:'Could not load operations report')).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const providerSummary=report?.providers.reduce((summary,provider)=>{const state=stateFor(provider);summary[state]++;summary.calls24h+=provider.calls_24h;return summary;},{healthy:0,warning:0,critical:0,idle:0,calls24h:0})??{healthy:0,warning:0,critical:0,idle:0,calls24h:0};
  return <div className="operations-page"><header className="operations-header"><div><span className="operations-eyebrow">Live operations</span><h2>Operations Centre</h2><p>Provider availability, service performance and campaign delivery in one place.</p></div><div className="operations-header-actions">{report&&<small>Updated {date(report.generated_at)}</small>}<button className="secondary" onClick={load} disabled={loading}>{loading?'Refreshing…':'Refresh data'}</button></div></header>
    <div className="operations-privacy"><span>✓</span><div><strong>Privacy-safe monitoring</strong><p>No credentials, request bodies, account numbers, phone numbers or customer identifiers are collected.</p></div></div>
    {error&&<div className="error-text">{error}</div>}{!report&&loading?<div className="card"><p className="muted">Loading operations health…</p></div>:report&&<>
      <section className="operations-overview"><article className="operations-metric good"><span>Healthy services</span><strong>{providerSummary.healthy}</strong><small>Operating normally</small></article><article className={`operations-metric ${providerSummary.critical?'bad':providerSummary.warning?'warn':'good'}`}><span>Services requiring attention</span><strong>{providerSummary.critical+providerSummary.warning}</strong><small>{providerSummary.critical} critical · {providerSummary.warning} warning</small></article><article className="operations-metric"><span>Provider calls</span><strong>{providerSummary.calls24h.toLocaleString()}</strong><small>During the last 24 hours</small></article><article className={report.recipients.failed?'operations-metric warn':'operations-metric'}><span>Email delivery queue</span><strong>{report.recipients.pending.toLocaleString()}</strong><small>{report.recipients.failed} awaiting retry</small></article></section>
      <section className="operations-delivery"><div><span>Active campaigns</span><strong>{report.campaigns.active}</strong></div><div><span>Emails accepted</span><strong>{report.recipients.sent.toLocaleString()}</strong></div><div><span>Delivery retries</span><strong>{report.recipients.failed.toLocaleString()}</strong></div><div><span>No recent activity</span><strong>{providerSummary.idle}</strong></div></section>
      <div className="card operations-provider-card"><div className="operations-card-header"><div><h3>Provider and service health</h3><p>Customer/input rejections are separated from genuine provider failures.</p></div><div className="operations-legend"><span><i className="healthy"/>Healthy</span><span><i className="warning"/>Warning</span><span><i className="critical"/>Critical</span><span><i className="idle"/>No activity</span></div></div>{report.providers.length===0?<div className="operations-empty"><h4>No provider services configured</h4><p>Add an active provider integration to begin monitoring.</p></div>:<div className="table-scroll operations-table"><table><thead><tr><th>Provider / service</th><th>Status</th><th>Calls<br/><small>15 min</small></th><th>Provider failures<br/><small>15 min</small></th><th>Customer rejections<br/><small>15 min</small></th><th>Latency<br/><small>avg / max</small></th><th>Failure rate<br/><small>24 hours</small></th><th>Last successful call</th><th/></tr></thead><tbody>{report.providers.map(p=>{const state=stateFor(p);return <Fragment key={`${p.provider}:${p.service}`}><tr><td><strong>{label(p.provider)}</strong><small className="operations-service-name">{label(p.service)}</small></td><td><span className={`health-pill ${state}`}>{state==='idle'?'No activity':state}</span></td><td><strong>{p.calls_15m}</strong></td><td className={p.failures_15m?'metric-bad':''}>{p.failures_15m} <small>({p.failure_rate_15m??0}%)</small></td><td>{p.client_errors_15m}</td><td>{p.avg_latency_15m??0} <small>/ {p.max_latency_15m??0} ms</small></td><td>{p.failures_24h}/{p.calls_24h} <small>({p.failure_rate_24h??0}%)</small></td><td>{date(p.last_success_at)}</td><td>{p.recent_issues.length>0&&<details className="provider-investigate"><summary>Investigate</summary><div className="provider-issue-panel"><div className="provider-issue-title"><strong>Recent provider issues</strong><span>Sanitized operational data only</span></div>{p.recent_issues.map((issue,index)=><p key={`${issue.occurred_at}:${index}`}><strong>{label(issue.operation)}</strong><span>{issue.error_code??issue.outcome}{issue.status_code?` · HTTP ${issue.status_code}`:''}</span><small>{date(issue.occurred_at)}</small></p>)}</div></details>}</td></tr></Fragment>;})}</tbody></table></div>}</div>
      <footer className="operations-footer"><span>Read-only monitoring</span><p>Monitoring never moves money or retries financial transactions.</p></footer>
    </>}</div>;
}
