import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { adminClient, readJsonBody, RequestBodyError } from "../_shared/auth.ts";
import { AdminAuthError, requireAdmin } from "../_shared/admin-auth.ts";
import { corsHeaders, handleCors } from "../_shared/cors.ts";
import { askGroq, isGroqConfigured } from "../_shared/groq-client.ts";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders(),"Content-Type":"application/json","Cache-Control":"no-store"}});
const range=(start:unknown,end:unknown)=>{const s=new Date(String(start??"")),e=new Date(String(end??""));if(!Number.isFinite(s.getTime())||!Number.isFinite(e.getTime())||e<=s||e.getTime()-s.getTime()>366*86400000)return null;return {start:s.toISOString(),end:e.toISOString()};};
serve(async req=>{const cors=handleCors(req);if(cors)return cors;let admin;try{admin=await requireAdmin(req,"support");}catch(error){if(error instanceof AdminAuthError)return json({error:error.message},error.status);return json({error:"Unauthorized"},401);}const db=adminClient();
 if(req.method==="GET"){const url=new URL(req.url),now=new Date(),period=range(url.searchParams.get("start")??new Date(now.getTime()-30*86400000),url.searchParams.get("end")??now);if(!period)return json({error:"Invalid report range"},400);const [business,profit,finance,markup,pnl,forecast,entries]=await Promise.all([db.rpc("admin_business_intelligence_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_profit_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_provider_finance_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_markup_commission_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_consolidated_pnl_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_financial_forecast_report",{p_as_of:now.toISOString()}),db.from("provider_finance_entries").select("id,provider,entry_type,amount_kobo,expense_category,reference,notes,occurred_at,created_at").order("occurred_at",{ascending:false}).limit(50)]);if(business.error||profit.error||finance.error||markup.error||pnl.error||forecast.error||entries.error)return json({error:"Could not prepare the business report"},500);await db.from("admin_actions").insert({admin_user_id:admin.userId,action_type:"business_intelligence_viewed",target_type:"business_report",metadata:{start:period.start,end:period.end}});return json({success:true,report:{...business.data,profit:profit.data,provider_finance:finance.data,markup_commission:markup.data,consolidated_pnl:pnl.data,financial_forecast:forecast.data,finance_entries:entries.data}});}
 if(req.method!=="POST")return json({error:"Method not allowed"},405);let body:Record<string,unknown>;try{body=await readJsonBody(req,4096);}catch(error){const e=error instanceof RequestBodyError?error:new RequestBodyError(400,"Invalid request");return json({error:e.message},e.status);}
 if(body.action==="record_finance_entry"){
  if(admin.role!=="super_admin")return json({error:"Not authorized"},403);
  const provider=typeof body.provider==="string"?body.provider.trim().toLowerCase():"",entryType=typeof body.entry_type==="string"?body.entry_type:"",amountNgn=Number(body.amount_ngn),category=typeof body.expense_category==="string"?body.expense_category.trim().toLowerCase().replace(/[^a-z0-9_-]/g,"_"):null,reference=typeof body.reference==="string"?body.reference.trim():null,notes=typeof body.notes==="string"?body.notes.trim():null,occurredAt=new Date(String(body.occurred_at??""));
  if(!["vtunaija","airalo","prembly"].includes(provider)||!["wallet_funding","funding_fee","operating_expense","balance_snapshot","adjustment"].includes(entryType)||!Number.isSafeInteger(Math.round(amountNgn*100))||amountNgn===0||(entryType!=="adjustment"&&amountNgn<0)||!Number.isFinite(occurredAt.getTime())||occurredAt.getTime()>Date.now()+300000||occurredAt.getTime()<new Date("2020-01-01").getTime()||(reference?.length??0)>120||(notes?.length??0)>500)return json({error:"Invalid finance entry"},400);
  const {data,error}=await db.from("provider_finance_entries").insert({provider,entry_type:entryType,amount_kobo:Math.round(amountNgn*100),expense_category:entryType==="operating_expense"?(category||"other"):null,reference:reference||null,notes:notes||null,occurred_at:occurredAt.toISOString(),created_by:admin.userId}).select("id").single();if(error)return json({error:"Finance entry could not be recorded"},500);
  await db.from("admin_actions").insert({admin_user_id:admin.userId,action_type:"provider_finance_entry_recorded",target_type:"provider_finance_entry",target_id:data.id,metadata:{provider,entry_type:entryType,amount_kobo:Math.round(amountNgn*100),expense_category:entryType==="operating_expense"?(category||"other"):null}});return json({success:true,id:data.id});
 }
 const period=range(body.start,body.end),prompt=typeof body.prompt==="string"?body.prompt.trim().slice(0,1000):"Prepare a concise management report covering performance, changes, risks and recommended next actions.";if(!period)return json({error:"Invalid report range"},400);if(!isGroqConfigured())return json({error:"AI reporting is unavailable"},503);const [business,profit,finance,markup,pnl,forecast]=await Promise.all([db.rpc("admin_business_intelligence_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_profit_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_provider_finance_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_markup_commission_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_consolidated_pnl_report",{p_start:period.start,p_end:period.end}),db.rpc("admin_financial_forecast_report",{p_as_of:period.end})]);if(business.error||profit.error||finance.error||markup.error||pnl.error||forecast.error)return json({error:"Could not prepare the business report"},500);const report={...business.data,profit:profit.data,provider_finance:finance.data,markup_commission:markup.data,consolidated_pnl:pnl.data,financial_forecast:forecast.data};try{const result=await askGroq(`${prompt}\nUse only the supplied aggregated report. This is a covered P&L and forecast, not statutory accounts. Always state coverage and missing balance snapshots; never extrapolate uncovered profit. Forecasts are projections, not actual earnings. Provider funding is an asset transfer, not an expense.`,{business_report:report});await db.from("admin_actions").insert({admin_user_id:admin.userId,action_type:"business_ai_report_generated",target_type:"business_report",metadata:{start:period.start,end:period.end,model:result.model,usage_limit:"provider_managed",cost_coverage_percent:profit.data?.coverage_percent,markup_coverage_percent:markup.data?.markup_coverage_percent}});return json({success:true,...result});}catch{return json({error:"AI report could not be generated"},503);}
});
