import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { adminClient, readJsonBody, RequestBodyError } from "../_shared/auth.ts";
import { AdminAuthError, requireAdmin } from "../_shared/admin-auth.ts";
import { corsHeaders, handleCors } from "../_shared/cors.ts";
import { diagnoseIncidentWithGroq, isGroqConfigured } from "../_shared/groq-client.ts";

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders(),"Content-Type":"application/json","Cache-Control":"no-store"}});
const FINGERPRINT=/^provider_[a-z0-9_-]{2,40}_[a-z0-9_-]{2,40}_health$/;
serve(async(req)=>{const cors=handleCors(req);if(cors)return cors;let admin;try{admin=await requireAdmin(req,"support");}catch(error){if(error instanceof AdminAuthError)return json({error:error.message},error.status);return json({error:"Unauthorized"},401);}const db=adminClient();
  if(req.method==="GET"){const [{data:alerts,error},operations,controls]=await Promise.all([db.from("monitoring_alerts").select("fingerprint,alert_type,severity,details,occurrence_count,first_seen_at,last_seen_at,status,acknowledged_at,resolved_at,resolution_notes,incident_analysis,analysis_model,analysis_generated_at").like("fingerprint","provider_%_health").order("last_seen_at",{ascending:false}).limit(100),db.rpc("provider_operations_report"),db.from("service_controls").select("service,enabled,reason")]);if(error||operations.error||controls.error)return json({error:"Could not load incident centre"},500);return json({success:true,incidents:alerts??[],operations:operations.data,service_controls:controls.data??[]});}
  if(req.method!=="POST")return json({error:"Method not allowed"},405);let body:Record<string,unknown>;try{body=await readJsonBody(req,2048);}catch(error){const e=error instanceof RequestBodyError?error:new RequestBodyError(400,"Invalid request");return json({error:e.message},e.status);}const fingerprint=String(body.fingerprint??""),action=String(body.action??""),notes=String(body.notes??"").trim();if(!FINGERPRINT.test(fingerprint))return json({error:"Invalid incident"},400);
  const {data:incident,error:incidentError}=await db.from("monitoring_alerts").select("fingerprint,alert_type,severity,details,occurrence_count,first_seen_at,last_seen_at,status").eq("fingerprint",fingerprint).maybeSingle();if(incidentError||!incident)return json({error:"Incident not found"},404);
  if(action==="analyze"){if(!isGroqConfigured())return json({error:"AI incident analysis is unavailable"},503);try{const diagnosis=await diagnoseIncidentWithGroq(incident);const now=new Date().toISOString();await db.from("monitoring_alerts").update({incident_analysis:diagnosis.analysis,analysis_model:diagnosis.model,analysis_generated_at:now}).eq("fingerprint",fingerprint);await db.from("admin_actions").insert({admin_user_id:admin.userId,action_type:"incident_ai_analysis_generated",target_type:"monitoring_alerts",target_id:fingerprint,metadata:{model:diagnosis.model}});return json({success:true,analysis:diagnosis.analysis,model:diagnosis.model,generated_at:now});}catch{return json({error:"AI analysis could not be generated. Detection remains active."},503);}}
  if(!["acknowledge","resolve","reopen"].includes(action))return json({error:"Invalid action"},400);if(action==="resolve"&&(notes.length<3||notes.length>500))return json({error:"Resolution notes must be 3 to 500 characters"},400);const now=new Date().toISOString();const changes=action==="acknowledge"?{status:"acknowledged",acknowledged_at:now,acknowledged_by:admin.userId,updated_at:now}:action==="resolve"?{status:"resolved",resolved_at:now,resolved_by:admin.userId,resolution_notes:notes,updated_at:now}:{status:"open",acknowledged_at:null,acknowledged_by:null,resolved_at:null,resolved_by:null,resolution_notes:null,updated_at:now};const {error}=await db.from("monitoring_alerts").update(changes).eq("fingerprint",fingerprint);if(error)return json({error:"Incident could not be updated"},500);await db.from("admin_actions").insert({admin_user_id:admin.userId,action_type:`incident_${action}`,target_type:"monitoring_alerts",target_id:fingerprint,reason:notes||null});return json({success:true,status:changes.status});
});
