import { formatNaira } from './formatCurrency';

// Every receipt builder here produces an HTML string for expo-print, built
// entirely from data already on the device (either a fresh purchase
// response, or a past transaction's own metadata) — nothing is ever
// generated on the server or stored as a file. Reused both right after a
// purchase (ElectricityPayScreen) and later from Transaction History
// (TransactionDetailModal), from two different data sources but the same
// template, so the receipt looks identical either way.
export function buildElectricityReceiptHtml(params: {
  providerName: string;
  meterType: string;
  meterNumber: string;
  amount: number;
  token: string | null;
  units: string | null;
  orderId?: string | null;
  date?: Date;
}): string {
  const { providerName, meterType, meterNumber, amount, token, units, orderId, date } = params;
  const when = date ?? new Date();
  const dateStr = when.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const timeStr = when.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #111; background: #f4f4ee; }
    .receipt { max-width: 480px; margin: 0 auto; background: #ffffff; border: 1px solid #ddd; border-radius: 10px; padding: 24px 28px; }
    .header { text-align: center; border-bottom: 2px solid #1a5c3a; padding-bottom: 14px; margin-bottom: 18px; }
    .header h1 { font-size: 16px; margin: 0; color: #1a5c3a; }
    .header h2 { font-size: 12px; margin: 4px 0 0; color: #777; font-weight: 500; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 8px 4px; font-size: 12.5px; border-bottom: 1px solid #eee; }
    td.label { color: #777; }
    td.value { font-weight: 700; color: #111; text-align: right; }
    .token-box { text-align: center; margin: 20px 0; padding: 16px; background: #e3f6ea; border-radius: 8px; }
    .token-label { font-size: 10px; color: #1a5c3a; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; }
    .token-value { font-size: 22px; font-weight: 800; letter-spacing: 3px; color: #111; margin-top: 6px; font-family: 'Courier New', monospace; }
    .units { font-size: 11.5px; color: #555; margin-top: 6px; }
    .footer { text-align: center; margin-top: 18px; font-size: 9.5px; color: #999; font-style: italic; }
  </style></head>
  <body>
    <div class="receipt">
      <div class="header">
        <h1>Electricity Payment Receipt</h1>
        <h2>${providerName}</h2>
      </div>
      <table>
        <tr><td class="label">Meter Type</td><td class="value">${meterType}</td></tr>
        <tr><td class="label">Meter Number</td><td class="value">${meterNumber}</td></tr>
        <tr><td class="label">Amount Paid</td><td class="value">${formatNaira(amount)}</td></tr>
        ${orderId ? `<tr><td class="label">Reference</td><td class="value">${orderId}</td></tr>` : ''}
        <tr><td class="label">Date</td><td class="value">${dateStr}</td></tr>
        <tr><td class="label">Time</td><td class="value">${timeStr}</td></tr>
      </table>
      ${token ? `
      <div class="token-box">
        <div class="token-label">Your Token</div>
        <div class="token-value">${token.replace(/(\d{4})(?=\d)/g, '$1 ')}</div>
        ${units ? `<div class="units">${units}</div>` : ''}
      </div>` : ''}
      <div class="footer">Keep this receipt for your records. Generated by Kay's Pay.</div>
    </div>
  </body></html>`;
}
