import { Asset } from 'expo-asset';
import { File } from 'expo-file-system';
import { formatNaira } from './formatCurrency';

// Every receipt builder here produces an HTML string for expo-print, built
// entirely from data already on the device (either a fresh purchase
// response, or a past transaction's own metadata) — nothing is ever
// generated on the server or stored as a file. Reused both right after a
// purchase (ElectricityPayScreen) and later from Transaction History
// (TransactionDetailModal), from two different data sources but the same
// template, so the receipt looks identical either way.
// Escapes the two fields sourced from VTUnaija's own verify response (not
// generated/typed by this app) before they're interpolated into the receipt
// HTML — everything else here is either server-validated (meter number is
// digit-only, providerName comes from our own static list) or app-generated.
function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function buildElectricityReceiptHtml(params: {
  providerName: string;
  meterType: string;
  meterNumber: string;
  amount: number;
  token: string | null;
  units: string | null;
  orderId?: string | null;
  date?: Date;
  customerName?: string | null;
  customerAddress?: string | null;
}): string {
  const { providerName, meterType, meterNumber, amount, token, units, orderId, date, customerName, customerAddress } = params;
  const when = date ?? new Date();
  const dateStr = when.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const timeStr = when.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #111; background: #f4f4ee; }
    .receipt { max-width: 480px; margin: 0 auto; background: #ffffff; border: 1px solid #ddd; border-radius: 10px; padding: 24px 28px; }
    .header { text-align: center; border-bottom: 2px solid #1a5c3a; padding-bottom: 14px; margin-bottom: 18px; }
    .header h1 { font-size: 16px; margin: 0; color: #1a5c3a; }
    .header h2 { font-size: 12px; margin: 4px 0 0; color: #777; font-weight: 500; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 8px 4px; font-size: 12.5px; border-bottom: 1px solid #eee; }
    td.label { color: #777; }
    td.value { font-weight: 700; color: #111; text-align: right; }
    .token-box { text-align: center; margin: 20px 0; padding: 16px; background: #e3f6ea; border-radius: 8px; }
    .token-label { font-size: 10px; color: #1a5c3a; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; }
    .token-value { font-size: 22px; font-weight: 800; letter-spacing: 3px; color: #111; margin-top: 6px; font-family: 'Courier New', monospace; }
    .units { font-size: 11.5px; color: #555; margin-top: 6px; }
    .footer { text-align: center; margin-top: 18px; font-size: 9.5px; color: #999; font-style: italic; }
  </style></head>
  <body>
    <div class="receipt">
      <div class="header">
        <h1>Electricity Payment Receipt</h1>
        <h2>${providerName}</h2>
      </div>
      <table>
        ${customerName ? `<tr><td class="label">Customer Name</td><td class="value">${escapeHtml(customerName)}</td></tr>` : ''}
        <tr><td class="label">Meter Type</td><td class="value">${meterType}</td></tr>
        <tr><td class="label">Meter Number</td><td class="value">${meterNumber}</td></tr>
        ${customerAddress ? `<tr><td class="label">Address</td><td class="value">${escapeHtml(customerAddress)}</td></tr>` : ''}
        <tr><td class="label">Amount Paid</td><td class="value">${formatNaira(amount)}</td></tr>
        ${orderId ? `<tr><td class="label">Reference</td><td class="value">${orderId}</td></tr>` : ''}
        <tr><td class="label">Date</td><td class="value">${dateStr}</td></tr>
        <tr><td class="label">Time</td><td class="value">${timeStr}</td></tr>
      </table>
      ${token ? `
      <div class="token-box">
        <div class="token-label">Your Token</div>
        <div class="token-value">${token.replace(/(\d{4})(?=\d)/g, '$1 ')}</div>
        ${units ? `<div class="units">${units}</div>` : ''}
      </div>` : ''}
      <div class="footer">Keep this receipt for your records. Generated by Kay's Pay.</div>
    </div>
  </body></html>`;
}

// Exam pin transactions previously fell through to the generic branded
// receipt below, which has no field for the PIN/Serial at all — so the
// downloaded/shared PDF showed the amount and date but never the actual PIN
// the customer paid for. This mirrors buildElectricityReceiptHtml's token-box
// pattern so the one-time PIN/Serial values are embedded in the PDF itself,
// not just shown on-screen.
export function buildExamPinReceiptHtml(params: {
  examName: string;
  amount: number;
  pins: string[];
  serials?: string[] | null;
  orderId?: string | null;
  date?: Date;
}): string {
  const { examName, amount, pins, serials, orderId, date } = params;
  const when = date ?? new Date();
  const dateStr = when.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const timeStr = when.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #111; background: #f4f4ee; }
    .receipt { max-width: 480px; margin: 0 auto; background: #ffffff; border: 1px solid #ddd; border-radius: 10px; padding: 24px 28px; }
    .header { text-align: center; border-bottom: 2px solid #1a5c3a; padding-bottom: 14px; margin-bottom: 18px; }
    .header h1 { font-size: 16px; margin: 0; color: #1a5c3a; }
    .header h2 { font-size: 12px; margin: 4px 0 0; color: #777; font-weight: 500; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 8px 4px; font-size: 12.5px; border-bottom: 1px solid #eee; }
    td.label { color: #777; }
    td.value { font-weight: 700; color: #111; text-align: right; }
    .token-box { text-align: center; margin: 20px 0; padding: 16px; background: #e3f6ea; border-radius: 8px; }
    .token-label { font-size: 10px; color: #1a5c3a; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; }
    .token-value { font-size: 18px; font-weight: 800; letter-spacing: 1px; color: #111; margin-top: 6px; font-family: 'Courier New', monospace; line-height: 1.6; }
    .footer { text-align: center; margin-top: 18px; font-size: 9.5px; color: #999; font-style: italic; }
  </style></head>
  <body>
    <div class="receipt">
      <div class="header">
        <h1>Exam PIN Receipt</h1>
        <h2>${escapeHtml(examName)}</h2>
      </div>
      <table>
        <tr><td class="label">Exam</td><td class="value">${escapeHtml(examName)}</td></tr>
        <tr><td class="label">Amount Paid</td><td class="value">${formatNaira(amount)}</td></tr>
        ${orderId ? `<tr><td class="label">Reference</td><td class="value">${escapeHtml(orderId)}</td></tr>` : ''}
        <tr><td class="label">Date</td><td class="value">${dateStr}</td></tr>
        <tr><td class="label">Time</td><td class="value">${timeStr}</td></tr>
      </table>
      <div class="token-box">
        <div class="token-label">${pins.length > 1 ? 'Your PINs' : 'Your PIN'}</div>
        <div class="token-value">${pins.map(escapeHtml).join('<br/>')}</div>
      </div>
      ${serials && serials.length ? `
      <div class="token-box">
        <div class="token-label">${serials.length > 1 ? 'Your Serials' : 'Your Serial'}</div>
        <div class="token-value">${serials.map(escapeHtml).join('<br/>')}</div>
      </div>` : ''}
      <div class="footer">Keep this receipt for your records. Generated by Kay's Pay.</div>
    </div>
  </body></html>`;
}

const CORRECTION_TITLES: Record<string, string> = {
  nin_name_modification: 'NIN Name Correction',
  nin_phone_modification: 'NIN Phone Number Correction',
  nin_address_modification: 'NIN Address Correction',
  nin_validation: 'NIN Validation',
};

// CheckMyNINBVN's own order-status response (confirmed against their docs,
// 2026-08-12) never returns the corrected personal-data record — only order
// metadata (reference_id, status, timestamps). So unlike the NIN/BVN Verify
// slips (which rebuild from a provider-confirmed record), this can only ever
// show what the USER submitted, not anything NIMC/the provider confirmed.
// The disclaimer below is load-bearing, not boilerplate — presenting this as
// an official corrected ID would be actively misleading in a financial app.
export function buildNinCorrectionReceiptHtml(params: {
  type: 'nin_name_modification' | 'nin_phone_modification' | 'nin_address_modification' | 'nin_validation';
  referenceId?: string | null;
  amount: number; // naira
  submittedAt: string; // ISO
  status: 'successful' | 'pending' | 'refunded' | 'failed';
  nin: string;
  dateOfBirth?: string; // validation only
  current?: { surname?: string; firstname?: string; middlename?: string; phoneNumber?: string };
  updated?: { surname?: string; firstname?: string; middlename?: string; phoneNumber?: string; address?: string };
}): string {
  const { type, referenceId, amount, submittedAt, status, nin, dateOfBirth, current, updated } = params;
  const title = CORRECTION_TITLES[type] || 'NIN Correction';
  const when = new Date(submittedAt);
  const dateStr = when.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const st = STATUS_STYLE[status.toLowerCase()] ?? STATUS_STYLE.pending;

  const fullName = (p?: { surname?: string; firstname?: string; middlename?: string }) =>
    p ? [p.firstname, p.middlename, p.surname].filter(Boolean).join(' ') || 'N/A' : 'N/A';

  let changeRows = '';
  if (type === 'nin_name_modification') {
    changeRows = `
      <tr><td class="label">Name on file (before)</td><td class="value">${escapeHtml(fullName(current))}</td></tr>
      <tr><td class="label">Corrected name (submitted)</td><td class="value">${escapeHtml(fullName(updated))}</td></tr>`;
  } else if (type === 'nin_phone_modification') {
    changeRows = `
      <tr><td class="label">New phone number (submitted)</td><td class="value">${escapeHtml(updated?.phoneNumber || 'N/A')}</td></tr>`;
  } else if (type === 'nin_address_modification') {
    changeRows = `
      <tr><td class="label">Phone on file</td><td class="value">${escapeHtml(current?.phoneNumber || 'N/A')}</td></tr>
      <tr><td class="label">Corrected address (submitted)</td><td class="value">${escapeHtml(updated?.address || 'N/A')}</td></tr>`;
  } else {
    changeRows = `<tr><td class="label">Date of Birth</td><td class="value">${escapeHtml(dateOfBirth || 'N/A')}</td></tr>`;
  }

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #111; background: #f4f4ee; }
    .receipt { max-width: 480px; margin: 0 auto; background: #ffffff; border: 1px solid #ddd; border-radius: 10px; padding: 24px 28px; }
    .header { text-align: center; border-bottom: 2px solid #1a5c3a; padding-bottom: 14px; margin-bottom: 18px; }
    .header h1 { font-size: 16px; margin: 0; color: #1a5c3a; }
    .header h2 { font-size: 12px; margin: 4px 0 0; color: #777; font-weight: 500; }
    .status-pill { display: inline-block; font-size: 11px; font-weight: 700; padding: 4px 10px; border-radius: 20px; margin-top: 10px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    td { padding: 8px 4px; font-size: 12.5px; border-bottom: 1px solid #eee; }
    td.label { color: #777; }
    td.value { font-weight: 700; color: #111; text-align: right; }
    .disclaimer { margin-top: 18px; padding: 12px 14px; background: #fff8e1; border: 1px solid #f0dca0; border-radius: 8px; font-size: 10.5px; color: #6b5a1f; line-height: 1.5; }
    .footer { text-align: center; margin-top: 18px; font-size: 9.5px; color: #999; font-style: italic; }
  </style></head>
  <body>
    <div class="receipt">
      <div class="header">
        <h1>${title} — Confirmation</h1>
        <h2>Kay's Pay</h2>
        <span class="status-pill" style="background:${st.bg};color:${st.fg}">${st.label}</span>
      </div>
      <table>
        <tr><td class="label">NIN</td><td class="value">${escapeHtml(nin)}</td></tr>
        ${changeRows}
        <tr><td class="label">Amount Charged</td><td class="value">${formatNaira(amount)}</td></tr>
        ${referenceId ? `<tr><td class="label">Reference</td><td class="value">${escapeHtml(referenceId)}</td></tr>` : ''}
        <tr><td class="label">Submitted</td><td class="value">${dateStr}</td></tr>
      </table>
      <div class="disclaimer">
        This confirms what you submitted to CheckMyNINBVN and its current outcome. It is <b>not an official NIMC identity document</b> — the provider does not return a corrected record for us to verify against. To get an updated, officially-verified NIN slip once this is approved, run a fresh NIN Verify.
      </div>
      <div class="footer">Generated by Kay's Pay · kayspay.com.ng</div>
    </div>
  </body></html>`;
}

const LOGO_ASSET = require('../../assets/icon-green.png');
let cachedLogoBase64: string | null = null;

// Resolves the bundled app icon to a base64 data URI for use inside
// expo-print's HTML (which can't reference RN require()'d assets directly)
// — same approach as NinServicesScreen.tsx's getEmblemBase64(). Cached
// after the first call since the asset never changes at runtime.
export async function getKaysPayLogoBase64(): Promise<string> {
  if (cachedLogoBase64) return cachedLogoBase64;
  const asset = Asset.fromModule(LOGO_ASSET);
  await asset.downloadAsync();
  const base64 = await new File(asset.localUri || asset.uri).base64();
  cachedLogoBase64 = `data:image/png;base64,${base64}`;
  return cachedLogoBase64;
}

const STATUS_STYLE: Record<string, { bg: string; fg: string; label: string }> = {
  successful: { bg: '#E3F6EA', fg: '#1A7A4A', label: 'Successful' },
  completed: { bg: '#E3F6EA', fg: '#1A7A4A', label: 'Successful' },
  pending: { bg: '#FEF3C7', fg: '#B45309', label: 'Pending' },
  failed: { bg: '#FEE2E2', fg: '#B91C1C', label: 'Failed' },
  refunded: { bg: '#F3F4F6', fg: '#4B5563', label: 'Refunded' },
};

// The universal, branded receipt for any transaction that doesn't already
// have its own specialized format (electricity's token receipt, the BVN/NIN
// slips) — the "Kuda-style" design the owner asked to standardize on:
// full-bleed brand header with the amount, a white detail card below,
// Download/Share actions, generated fresh from the transaction's own data
// every time (no PDF is ever stored — same rule as every other receipt here).
export async function buildTransactionReceiptHtml(params: {
  label: string; // e.g. "MTN Airtime", "GLO Data Bundle", "Wallet Funding"
  recipient?: string | null;
  network?: string | null;
  amount: number; // naira
  senderName: string;
  timestamp: string; // ISO
  reference?: string | null;
  status: string;
}): Promise<string> {
  const { label, recipient, network, amount, senderName, timestamp, reference, status } = params;
  const logo = await getKaysPayLogoBase64();
  const when = new Date(timestamp);
  const dateStr = when.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const timeStr = when.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
  const st = STATUS_STYLE[status.toLowerCase()] ?? STATUS_STYLE.pending;

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 0; margin: 0; background: #f4f4ee; }
    .receipt { max-width: 420px; margin: 24px auto; border-radius: 20px; overflow: hidden; background: #123626; }
    .header { padding: 32px 24px 26px; text-align: center; }
    .brand-row { display: inline-flex; align-items: center; gap: 8px; margin-bottom: 22px; }
    .brand-tile { width: 30px; height: 30px; border-radius: 8px; }
    .brand-name { font-size: 20px; font-weight: 800; color: #ffffff; letter-spacing: 0.3px; }
    .amount-label { font-size: 11px; letter-spacing: 1.5px; color: rgba(255,255,255,0.65); margin-bottom: 8px; }
    .amount { font-size: 34px; font-weight: 800; color: #ffffff; }
    .card { background: #ffffff; border-radius: 20px 20px 0 0; padding: 22px 24px 26px; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 12px 0; font-size: 13px; border-bottom: 1px solid #efefef; vertical-align: top; }
    td.label { color: #8a8a8a; width: 35%; }
    td.value { font-weight: 700; color: #111111; text-align: right; }
    td.value .sub { display: block; font-weight: 500; color: #8a8a8a; font-size: 11px; margin-top: 2px; }
    .status-pill { display: inline-block; font-size: 11px; font-weight: 700; padding: 4px 10px; border-radius: 20px; }
    .footer { text-align: center; margin-top: 18px; font-size: 10px; color: #b0b0b0; font-style: italic; }
  </style></head>
  <body>
    <div class="receipt">
      <div class="header">
        <div class="brand-row">
          <img src="${logo}" class="brand-tile" style="width:30px;height:30px;border-radius:8px;object-fit:contain;" />
          <span class="brand-name">Kay's Pay</span>
        </div>
        <div class="amount-label">TRANSACTION AMOUNT</div>
        <div class="amount">${formatNaira(amount)}</div>
      </div>
      <div class="card">
        <table>
          ${recipient ? `<tr><td class="label">Recipient</td><td class="value">${escapeHtml(recipient)}${network ? `<span class="sub">${escapeHtml(network)}</span>` : ''}</td></tr>` : ''}
          <tr><td class="label">Sender</td><td class="value">${escapeHtml(senderName)}<span class="sub">Kay's Pay Wallet</span></td></tr>
          <tr><td class="label">Paid on</td><td class="value">${dateStr}<span class="sub">${timeStr}</span></td></tr>
          <tr><td class="label">Description</td><td class="value">${escapeHtml(label)}</td></tr>
          ${reference ? `<tr><td class="label">Reference</td><td class="value">${escapeHtml(reference)}</td></tr>` : ''}
          <tr><td class="label">Status</td><td class="value"><span class="status-pill" style="background:${st.bg};color:${st.fg}">${st.label}</span></td></tr>
        </table>
        <div class="footer">Generated by Kay's Pay · kayspay.com.ng</div>
      </div>
    </div>
  </body></html>`;
}
