import type { Metadata } from "next";
import { notFound } from "next/navigation";
import StoreButton from "../StoreButton";

const cryptoAssets = [
  ["USDT", "Tether", "usdt.png"],
  ["BTC", "Bitcoin", "btc.png"],
  ["ETH", "Ethereum", "eth.png"],
  ["SOL", "Solana", "sol.png"],
  ["XRP", "XRP", "xrp.png"],
  ["TRX", "TRON", "trx.png"],
  ["LTC", "Litecoin", "ltc.png"],
  ["DOGE", "Dogecoin", "doge.png"],
  ["ADA", "Cardano", "ada.png"],
] as const;

const tvPartners = [
  ["DStv", "dstv.png"],
  ["GOtv", "gotv.png"],
  ["StarTimes", "startimes.png"],
] as const;

const pages = {
  services:{title:"Digital Services in Nigeria",intro:"Explore supported airtime, data, bills, subscriptions and other everyday digital services available through KaysPay.",items:[["Airtime and data","Top up supported Nigerian mobile networks and review available data plans."],["Electricity bills","Pay supported distribution companies using the account or meter details requested in the app."],["TV subscriptions","Renew supported DStv, GOtv and StarTimes packages."],["Exam products","Purchase supported examination and result-checking products."],["Travel connectivity","Browse eSIM packages for supported countries and destinations."],["Identity and other services","Access supported identity and other digital services when available and eligible."]]},
  "airtime-data":{title:"Buy Airtime and Data Online in Nigeria",intro:"Use KaysPay to top up supported Nigerian mobile networks and choose from available data plans.",items:[["Supported networks","Available products can include MTN, Airtel, Glo and 9mobile. Check the app for the latest network availability."],["Review before payment","Confirm the phone number, network, plan allowance, validity period and final price before purchasing."],["Discounts and cashback","Eligible data plans may receive an automatic discount, cashback or both. The app shows applicable benefits before confirmation."],["Transaction status","Every purchase receives a trackable status. Avoid repeating a transaction while the first request remains pending."]]},
  "electricity-bills":{title:"Pay Electricity Bills Online in Nigeria",intro:"Pay supported prepaid and postpaid electricity accounts through KaysPay.",items:[["Supported billers","Availability can include major Nigerian electricity distribution companies. The current list is shown in the app."],["Meter and account details","Enter the requested meter or account information carefully and verify the customer details displayed before payment."],["Prepaid tokens","When a successful prepaid purchase returns a meter token, keep the transaction receipt for reference."],["Pending payments","Do not immediately pay again when a transaction is pending. Check its final status or contact support with the reference."]]},
  "tv-subscriptions":{title:"Renew DStv, GOtv and StarTimes Online",intro:"Use KaysPay to renew supported television subscription packages.",items:[["Supported television services","Available billers can include DStv, GOtv and StarTimes."],["Customer information","Review the smartcard or customer number and the displayed account information before confirming."],["Package availability","Packages and prices can change through the service provider. KaysPay displays the latest available options before payment."],["Payment records","Successful and pending subscription payments appear in your transaction history."]]},
  "exam-pins":{title:"Buy Exam and Result Checker PINs Online",intro:"Purchase supported examination and result-checking products through KaysPay.",items:[["Supported products","Available products may include supported examination registration or result-checking PINs."],["Review the product","Confirm the examination body, product type, quantity and final amount before payment."],["Keep your PIN private","Treat purchased PINs and serial numbers as sensitive. Do not post them publicly or share them with unknown persons."],["Receipts and history","Where supported, purchased details and transaction records remain available from the relevant order or receipt flow."]]},
  "travel-esim":{title:"Buy Travel eSIM Data Plans",intro:"Browse supported mobile-data eSIM packages for international travel and connectivity.",items:[["Destination coverage","Search supported countries and review the coverage information for the selected package."],["Device compatibility","Confirm that your phone supports eSIM and is network-unlocked before purchasing."],["Plan details","Review the allowance, validity period, activation terms and price before payment."],["Important limitation","An eSIM package does not guarantee coverage in every location. Local network conditions and provider availability apply."]]},
  "identity-services":{title:"Supported NIN and BVN Services",intro:"Access supported identity verification and document services when available and eligible.",items:[["Eligibility","Identity services require accurate customer information and may include additional authorization or verification steps."],["Sensitive information","Only submit identity information through the official KaysPay app. Never send full identity records through social media."],["Provider outcomes","Results depend on the relevant authorized data source and service provider."],["Privacy","KaysPay processes identity information only for the service requested and according to its privacy terms."]]},
  "crypto-services":{title:"Buy, Hold and Sell Crypto with KaysPay",intro:"Buy supported cryptocurrencies directly with naira, hold them in your KaysPay wallet, and sell supported assets with automatic naira payment to your verified bank account.",items:[["Buy crypto with naira","Choose a supported cryptocurrency, enter the naira amount and review your live quote before confirming your purchase."],["Hold crypto in your KaysPay wallet","Keep your purchased cryptocurrency in your KaysPay wallet and view your available balances conveniently from the app."],["Automatic bank payout","When you sell a supported cryptocurrency, the naira proceeds are sent automatically to your verified bank account."],["Clear rates before confirmation","See the exchange rate, applicable charges and expected crypto or naira amount before completing a transaction."],["Simple, guided experience","Follow clear steps designed to make buying, holding and selling crypto straightforward, even when you are getting started."],["Track every transaction","Monitor the status of your crypto activity and access completed transaction records from your KaysPay history."]]},
  security:{title:"Security",intro:"Controls designed to protect accounts, transactions and personal information.",items:[["Transaction authorization","Sensitive actions require fresh authorization rather than relying only on a signed-in session."],["Server-side processing","Balances, pricing and financial decisions are verified on protected server systems."],["Account protection","Administrative access uses role checks and multi-factor authentication."],["Auditability","Financial activity is recorded so failures and disputes can be investigated."],["Privacy","KaysPay collects and shares only information needed to provide requested services."],["Honest limits","No digital service can promise absolute security; controls are monitored and improved continuously."]]},
  about:{title:"About KaysPay",intro:"Simple, dependable tools for the payments people make most often.",items:[["Our company","KaysPay is a product of Kay's Limited (RC 9705891), incorporated in Nigeria."],["Our focus","Clear customer journeys for airtime, data, bills and other supported services."],["Our approach","Practical design for varying network quality, older Android devices and everyday Nigerian use."],["Service providers","Transactions are fulfilled through relevant third-party payment, telecom and service providers."]]},
  help:{title:"Help and Frequently Asked Questions",intro:"Answers to common questions before you contact KaysPay support.",items:[["A purchase is pending","Check your transaction history first. Do not repeat a payment while the original transaction is still being confirmed."],["A transaction failed","Eligible failed transactions are reviewed for reversal or refund according to the service outcome."],["My price changed","Provider prices can change. KaysPay asks you to review the latest amount before confirming."],["I cannot access my account","Use the available recovery flow or contact support from your registered email address."],["How do I delete my account?","Follow the account-deletion instructions linked in the website footer."],["Need more help?","Email support@kayspay.com.ng with the transaction reference, but never send your password, PIN or OTP."]]},
  contact:{title:"Contact KaysPay",intro:"Customer support, business and regulatory enquiries.",items:[["Customer support","support@kayspay.com.ng"],["Registered company","Kay's Limited — RC 9705891"],["Registered office","Shop 25, Chindah Shopping Plaza, Rivers State University Main Gate, Port Harcourt, Rivers State, Nigeria."],["Security reminder","KaysPay support will never ask for your password, transaction PIN or one-time code."]]},
} as const;

export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const page=pages[slug as keyof typeof pages];return page?{title:page.title,description:page.intro,alternates:{canonical:`/${slug}/`},openGraph:{title:`${page.title} | KaysPay`,description:page.intro,url:`https://kayspay.com.ng/${slug}/`}}:{title:"Not found"};}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug as keyof typeof pages];if(!page)notFound();return <section className={`page shell${slug==="crypto-services"?" crypto-page":""}`}><span className="eyebrow">KaysPay</span><h1>{page.title}</h1><p className="lead">{page.intro}</p>{slug==="crypto-services"&&<section className="crypto-assets" aria-labelledby="supported-crypto-title"><div><span className="eyebrow">Supported cryptocurrencies</span><h2 id="supported-crypto-title">Choose from popular digital assets</h2><p>Buy with naira and hold supported assets directly in your KaysPay wallet.</p></div><div className="crypto-logo-grid">{cryptoAssets.map(([code,name,file])=><article key={code}><img src={`/images/crypto/${file}`} alt={`${name} logo`}/><span><strong>{code}</strong><small>{name}</small></span></article>)}</div></section>}{slug==="tv-subscriptions"&&<section className="tv-partners" aria-labelledby="supported-tv-title"><div><span className="eyebrow">Supported TV partners</span><h2 id="supported-tv-title">Your favourite television services</h2><p>Renew supported DStv, GOtv and StarTimes packages conveniently through KaysPay.</p></div><div className="tv-logo-grid">{tvPartners.map(([name,file])=><article key={name}><img src={`/images/providers/${file}`} alt={`${name} logo`}/><strong>{name}</strong></article>)}</div></section>}<div className="content-grid">{page.items.map(([title,description])=><article key={title}><h2>{title}</h2><p>{description}</p></article>)}</div><div className="page-cta"><span><strong>Ready to use KaysPay?</strong><small>Free on Android. Create your account in minutes.</small></span><StoreButton location={`page_${slug}`} className="button" /></div></section>}
